CONTRIBUTING.md

Update:https://github.com/gluster/glusto-tests/issues/35

[Doc] Updating CONTRIBUTING.md to GitHub workflow

---

tests/functional/arbiter/test_verify_metadata_and_data_heal.py

Test: test_gfid_heal_from_shd
Steps:
- Create and mount a volume
- Set `self-heal-daemon` to `off`, cyclic brick down and perform gfid
operations
- Set `self-heal-daemon` to `on` and wait for heal completion
- Validate areequal checksum on backend bricks
Test: test_file_type_differs_heal_from_shd
Steps:
- Create and mount a volume
- Set `self-heal-daemon` to `off`, cyclic brick down and perform gfid
opertions differing in file types
- Set `self-heal-daemon` to `on` and wait for heal completion
- Validate areequal checksum on backend bricks
Test: test_sym_link_heal_from_shd
Steps:
- Create, mount and run IO on volume
- Set `self-heal-daemon` to `off`, cyclic brick down and perform
symlink operations
- Set `self-heal-daemon` to `on` and wait for heal completion
- Validate areequal checksum …

[Test] Verify gfid self heal

---

tests/functional/arbiter/test_data_self_heal_algorithm_diff_default.py

[Test] Add rep and distrep to test_data_self_heal_algorithm_diff_default

---

tests/functional/dht/test_brick_full_add_brick_rebalance.py
tests/functional/disperse/test_ec_io_hang_serverside_heal.py

[Testfix] Additional fixes for tier1 cases

---

tests/functional/authentication/test_auth_allow_reject_same_client.py

Signed-off-by: Manisha Saini <msaini@msaini.blr.csb>

[Test] Test auth allow and auth reject with same client

---

tests/functional/disperse/test_ec_all_healtypes.py

Signed-off-by: UpasanaBansal <ubansal@redhat.com>

[TestFix] Add all heal for replicate and distributed replcate

---

tests/functional/authentication/test_auth_allow_with_rebalance.py

Signed-off-by: Manisha Saini <msaini@msaini.blr.csb>

[Test] Verify auth functionality with rebalance

---

tests/functional/nfs_ganesha/root-squash/test_nfs_ganesha_root_squash_mount_unmount.py

Signed-off-by: Manisha Saini <msaini@msaini.blr.csb>

[Test] Test root-squash functionality with volume remount

---

tests/functional/afr/test_replica_eager_lock.py

Signed-off-by: Sri Vignesh <sselvan@redhat.com>

[Test] Add test to validate replica eager-lock and volume profile

---

tests/functional/afr/test_replica_eager_lock.py

Signed-off-by: Sri Vignesh <sselvan@redhat.com>

[Test-Fix] Add distribute replica as part of tc

---

tests/functional/afr/test_self_heal_with_full_algorithm.py

Steps:
1. Create a replicated/distributed-replicate volume and mount it
2. Set data/metadata/entry-self-heal to off and
data-self-heal-algorithm to full
3. Create a directory from the mount point
4. Bring down all bricks from a selected set
5. Create few files inside the directory with some data
6. Bring back the bricks online and wait for heal to complete
7. Check arequal of the subvol and all the bricks in the subvol should
have same checksum
8. Bring down all bricks from another set
9. Modify the data of existing files under the directory
10. Bring back the bricks online and wait for heal to complete
11. Check arequal of the subvol and all the brick in the same subvol
should have same checksum
Signed-off-by: karthik-us <ksubrahm@redhat.com>

[Test] - Check self heal with data-self-heal-algorithm set to full

---

glustolibs-gluster/glustolibs/gluster/volume_ops.py

Signed-off-by: Aditya Ramteke <aramteke@redhat.com>

[LibFix] Remove getchildren from get_volume_list as deprecated

---

tests/functional/glusterd/test_glusterd_start_stop_output.py

Change-Id: Ia5a3f7df990360bbdc964c49496dea7399d499ab

[TestFix] Set1: Review of failing glusterd tests

---

glustolibs-gluster/glustolibs/gluster/lib_utils.py

Signed-off-by: Sri Vignesh <vigneshsri11@gmail.com>

[Lib] Add epel release repo for rhel8

---

glustolibs-gluster/glustolibs/gluster/lib_utils.py
tests/functional/afr/heal/test_heal_info_no_hang.py
tests/functional/afr/test_arb_to_repl_conversion_with_io.py
tests/functional/afr/test_self_heal_with_full_algorithm.py
tests/functional/afr/test_split_brain_with_hard_link_file.py

Change-Id: Ic0c156da244c3c4543547c513504f05627388ada

[TestFix] Fix AFR Failing tests

---

tests/functional/nfs_ganesha/root-squash/test_nfs_ganesha_root_squash.py
tests/functional/nfs_ganesha/root-squash/test_nfs_ganesha_root_squash_multiple_client.py
tests/functional/nfs_ganesha/root-squash/test_root_squash_with_glusterd_restart.py
tests/functional/nfs_ganesha/root-squash/test_root_squash_with_volume_restart.py

[LibFix] Name fix for root_squash Tests

---

glustolibs-gluster/glustolibs/gluster/gluster_base_class.py

Fix for issue #90 
Signed-off-by: Sri Vignesh <vigneshsri11@gmail.com>

[LibFix] Fix cleanup error

---

tests/functional/afr/test_self_heal_with_full_algorithm.py

Change-Id: I383a1a8d0fe8c850a6412de212c0056c528c2015

Use correct assert statement

---

glustolibs-gluster/glustolibs/gluster/samba_libs.py

Adding ctdb setup code to samba library.

Added ctdb setup to samba_libs

---

glustolibs-gluster/glustolibs/gluster/samba_libs.py

Added samba-ctdb volume options to samba_libs

Added samba-ctdb volume option condition.
