gluster/glusto-tests

- tests/functional/afr/test_client_io_threads_on_replicated_volumes.py
Test Scenario:
------------------
Test case 1:
1. Create distrubuted volume and start it.
2. Check the value of performance.client-io-threads it should be ON.
3. io-threads should be loaded in trusted-.tcp-fuse.vol.
4. Add brick to convert to replicate volume.
5. Check the value of performance.client-io-threads it should be OFF.
6. io-threads shouldn't be loaded in trusted-.tcp-fuse.vol.
7. Remove brick so thate volume type is back to distributed.
8. Check the value of performance.client-io-threads it should be ON.
9. performance.client-io-threads should be loaded in trusted-.tcp-fuse.vol.
Test case 2:
1. Create a replicate volume and start it.
2. Set performance.client-io-threads to ON.
3. Check the value of performance.client-io-threads it should be ON.
4. io-threads should be loaded in …
> [Test] Add test for performance.client-io-threads with afr volumes

- tests/functional/tier4/test_compile_linux_kernel_with_self_heal.py
Test Case:
1. Create a volume of any type, start it and mount it.
2. Perform linux untar on the mount point and wait for it to complete.
3. Bring down brick processes of volume.
4. Compile linux kernel on monut point.
5. Bring offline bricks back online.
6. Wait for heal to complete.
7. Check arequal checksum on bricks and make sure there is
no data loss.
> [Test] Add test to compile linux kernel with self-heal

- tests/functional/afr/heal/test_self_heal_with_link_files.py
- tests/functional/dht/test_brick_full_add_brick_rebalance.py
- tests/functional/dht/test_rebalance_add_brick_command.py
- tests/functional/snapshot/test_snapshot_restore.py
Problems:
---------
test_self_heal_with_link_files.py fails as granular entry heal
creates a directory which causes aqreual-checksum mismatch.
test_brick_full_add_brick_rebalance.py fails with
`fallocate: fallocate failed: No space left on device` which
happens as the volume gets filled quicker than expected.
test_rebalance_add_brick_command.py fails with disperse volumes
as it runs `expand_volume()` till the bricks is exhausted.
test_snapshot_restore.py `if not ret` causes teardown failures
even when the command was successful.
Fixes:
------
test_self_heal_with_link_files.py - Update to support granualar entry heal.
test_brick_full_add_brick_rebalance.py - Modify code to not fail on I/O.
test_rebalance_add_brick_command.py - Modify code to not run expand_volume
4 times. …
> [Testfix] Fix tier1 test case failures

- tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
Test Steps:
1. Restart glusterd on one of the node.
2. Check friend updates that happened between nodes where
glusterd was running.
3. Check friend updates between a rejoined node to each other node.
Signed-off-by: nik-redhat <nladha@redhat.com>
> [Test]: Add tc to check friend updates when a node rejoins

- tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py
Test Steps:
1. Create and start a volume
2. Enable quota on the volume
2. Fuse mount the volume
3. Get the glusterd statedump and analyze the statedump
4. Enable client-side quorum on the volume
5. Get the glusterd statedump
6. Delete the volume and peer detach 2 nodes
7. Create a replica 2 volume and start it
8. Kill the first brick of the volume
9. Get the glusterd statedump
10. Start the volume with force
11. Enable server-side quorum on the volume
12. Get the glusterd statedump
13. Stop glusterd on one of the node
14. Get the glusterd statedump
15. Stop glusterd on another node
16. Get the glusterd statedump
Didn't add the code to analyze SHD, because the stats for it
is not checked using the statedump from `glusterfs` process.
Signed-off-by: nik-redhat <nladha@redhat.com>
> [Test]: Add tc to check statedump when server,client quorum set on volume

- tests/functional/glusterfind/test_glusterfind_when_node_down.py
Glusterd is downed in a given node. Added a check
to wait till it has stopped completely.
Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>
> [Testfix] Adding check for node-down.

- tests/functional/glusterd/test_brickmux_brick_process.py
1. Create a 3 node cluster.
2. Set cluster.brick-multiplex to enable.
3. Create 15 volumes of type replica 1x3.
4. Start all the volumes one by one.
5. While the volumes are starting reboot one node.
6. check for pifof glusterfsd single process should be visible
Signed-off-by: milindw96 mwaykole@redhat.com
> [Test] Seen multiple brick Process while  starting volume node Reboot

- tests/functional/arbiter/test_metadata_self_heal.py
- tests/functional/arbiter/test_split_brain.py
Problem:
-------
test_metadata_self_heal.py - trigger_heal() function call isn't needed
as heal is automatically triggered when shd is enabled back.
test_split_brain.py - Test case fails in tearDownClass() as
doCleanups() cleans up the setup before invoking tearDownClass().
Solution:
---------
test_metadata_self_heal.py - Removing trigger_heal() function call.
test_split_brain.py - Change tearDownClass() to tearDown().
> [TestFix] Remove trigger_heal and change to tearDown in arbiter cases

- glustolibs-gluster/glustolibs/gluster/lib_utils.py
- tests/functional/glusterd/test_gluster_operations_after_removing_firewall.py
Test Steps:
1. Add firewall services to the zones on 2 nodes
2. Create a cluster using the 2 nodes
3. Check peer status on both the nodes
4. Remove firewall services from both the nodes
5. Check peer status on both the nodes
6. Create a distribute volume using both the node bricks and start it
7. Mount the volume on different node, it should fail
8. Cleanup the volume, Detach the node and try to probe again
9. Check peer status
10. Remove firewall services permanently and reload firewall
11. Check peer status
12. Create a distribute volume using both the node bricks and start it
13. Mount the volume on different node, it should fail
Note to reviewers:
Modified a few steps as per the working of the test case.
Signed-off-by: nik-redhat <nladha@redhat.com>
> [Test]: Add tc to check gluster operations after removing firewall

- tests/functional/dht/test_verify_rebalance_with_locks_on_files.py
Test Steps:
1. Create a distributed or distributed-replicate volume and
populate some data
2. Hold exclusive lock on a file (can use flock)
3. Add-brick and rebalance (make sure this file gets migrated)
4. Again from another program try to hold exclusive lock on this file
Signed-off-by: Pranav <prprakas@redhat.com>
> [Test] Add test to validate rebalance with locks on files

- tests/functional/glusterd/test_glusterd_start_stop_output.py
Test Case:
1. Stop and Start glusterd and store the output returned.
2. Check if consistent output is returned if glusterd is started and
stopped 5 times.
Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>
> [Test] Glusterd start-stop consistent info

- tests/functional/ctime_feature/test_ctime_updated_if_mtime_is_updated.py
Test Case:
1. test with features.ctime enabled
2. touch /mnt/file1
3. stat /mnt/file1
4. sleep 1;
5. touch -m -d "2020-01-01 12:00:00" /mnt/file1
6. stat /mnt/file1
Signed-off-by: milindw96 <milindwaykole96@gmail.com>
> [Test]Add Check ctime update when m|atime changed

- tests/functional/glusterd/test_validate_optimized_glusterd_handshake_for_2000_volumes.py
Test Steps:
1) Create a 3 node cluster
2) Enable brick-multiplex in the cluster
3) Create and start 2000 volumes
4) Stop one of the nodes in the cluster
5) Set an option for around 850 volumes in the cluster
6) Restart glusterd on the previous node
7) Check the value of the option set earlier, in the restarted node
Signed-off-by: nik-redhat <nladha@redhat.com>
> [Test]: Add tc to validate optimised handshake by glusterd with 2000 volumes

- tests/functional/glusterd/test_custom_xlator.py
Steps:
- Perform minimal IO on the mount
- Enable custom xlator and verify xlator position in the volfile
- After performing any operation on the custom xlator set options
using 'storage.reserve' to validate other xlators aren't effected
- Add brick to the volume and verify the xlator position in volfile in
the new brick
- Replace brick and verify the xlator position in new brick volfile
- Verify debug xlator is reflected correctly in the volfile when set
- Validate unexisting xlator position should fail
- Reset the volume and verify all the options set above are reset
Change-Id: I5e9dad797fe187b3b9bcdd7374635779c97c5f25
> [Test] Validate custom-xlator framework

- glustolibs-gluster/glustolibs/gluster/heal_ops.py
- glustolibs-gluster/glustolibs/gluster/peer_ops.py
- glustolibs-gluster/glustolibs/gluster/profile_ops.py
- glustolibs-gluster/glustolibs/gluster/quota_ops.py
- glustolibs-gluster/glustolibs/gluster/rebalance_ops.py
- glustolibs-gluster/glustolibs/gluster/snap_ops.py
- glustolibs-gluster/glustolibs/gluster/volume_libs.py
- glustolibs-gluster/glustolibs/gluster/volume_ops.py
Removing getchildren() as it is deprecated from python 3.2.
Some of the OCS test cases are failing with python3.
Signed-off-by: Aditya Ramteke <aramteke@redhat.com>
> [LibFix] Removing getchildren from glustolibs as deprecated

- tests/functional/bvt/test_sosreport_interoperability.py
Fixing the comaprison logic for dirs before SOS report
generation and after
Problem:
The current approach is using `==` operator for comparing
two lists. The issue happens when the lists are in different
order,
for e.g:
>>>a = [1,2,3]
>>>b = [1,3,2]
>>>a == b
False
The comparison returns False, whereas the content of the lists
are same.
Solution:
Use set() instead to ensure that the contents are similar,
E.g.
>>> set(a) - set(b)
set()
Signed-off-by: Pranav <prprakas@redhat.com>
> [TestFix] Fix test_sosreport_interoperability.py

- tests/functional/dht/test_rebalance_add_brick_and_lookup.py
Problem:
The current approach compares the lookup time with a
predetermined time of 4.4 secs (It took	4 seconds in
RHGS 3.5.2 and keeping a buffer of 10%). But this value
is machine is specific and vairies accordingly with
machines. For e.g, below are the time taken when executed
the above tests	locally
```
Glusterfs 49
Lookup took : 19 seconds (distributed)
Lookup took : 14 seconds (distributed-replicated)
Lookup took : 14 seconds (distributed-dispersed)
Lookup took : 14 seconds (distributed-arbiter)
Glusterfs 56.2
Lookup took : 15 seconds (distributed)
Lookup took : 10 seconds (distributed-replicated)
Lookup took : 13 seconds (distributed-dispersed)
Lookup took : 11 seconds (distributed-arbiter)
Glusterfs 59
Lookup took : 15 seconds (distributed)
Lookup took : 10 seconds …
```
> [TestFix] Fix test_rebalance_with_add_brick_and_lookup

- tests/functional/dht/test_verify_permissions_on_root_dir_when_brick_down.py
Problem:
The test was failing due to the following issues:
[1] File permissions were set using `self.clients[0]` whereas
the mount was done using `self.mounts[0]`. The data in these
two lists are identical but the position can change, which
causes 'directory not found' issue while setting permissions.
[2] `bring_bricks_online` method access lists of bricks which
are down.
Solution:
[1] Replace `self.clients[0]` with `self.mounts[0]`
[2] Sent list of bricks to the method
Signed-off-by: Pranav <prprakas@redhat.com>
> [TestFix] Fix test_verify_permissions_on_root_dir_when_brick_down.py

- tests/functional/arbiter/test_handling_data_split_brain_of_files_heal_command.py
- Test description states to enable shd but misses it in steps
- Adding missing step based on description
- Tested locally and the heal is successful
Change-Id: I562a5f75bc9561b8f6b68e5a338af494aca3d150
> [TestFix] Fix Arbiter test failures

- tests/functional/arbiter/test_metadata_self_heal_on_open_fd.py
Problem:
Method "get_heal_info_summary" returns dict with 'hostnames' as
keys in CI env and in the test we are using 'bricks_list' items, which
contains ip addr for accessing the above dict. This causes the
test to fail with 'KeyError' in CI env
Solution:
Change the logic to append hostnames in 'bricks_list' instead of
ip addr
Signed-off-by: Pranav <prprakas@redhat.com>
> [TestFix] Fix test_metadata_self_heal_on_open_fd
